version: '3'
services:
    timescaledb:
        image: timescale/timescaledb:1.5.0-pg10
        volumes:
            - /mnt/db/pgdata:/var/lib/postgresql/data
        command: postgres -cmax_wal_size=10GB

    timescaledb-initialize:
        build:
            context: ..
            dockerfile: ./timescaledb/Dockerfile
        depends_on:
            - timescaledb
        links:
            - timescaledb

    aggandprivacy:
        image: opalservices/opal-privacy:latest@sha256:1eee59a977738eca62a0b25d94aa70a60b5cf4ea5f9f39e1c091fbbcf19d3803
        command: sh -c 'npm start'
        volumes:
            - ./opal.privacy.config.js:/usr/app/config/opal.privacy.config.js

    compute:
        image: opalservices/opal-compute:latest@sha256:00d2dedc99d88dcc659c43371b4ffa93ad036208d5c09fe252790df965619dba
        command: sh -c 'sudo apparmor_init && sleep 5 && sudo npm start'
        privileged: true
        security_opt:
            - apparmor:unconfined
        volumes:
            - ./opal.compute.config.js:/home/opal/app/config/opal.compute.config.js

    scheduler:
        image: opalservices/opal-scheduler:latest@sha256:7fc5fdf86db0fef3b3ee4d0c78a4d2edb3d54509a5a4720ae1a8275d38a57288
        depends_on:
            - compute
        links:
            - compute
        volumes:
            - ./opal.scheduler.config.js:/usr/app/config/opal.scheduler.config.js
